#%RAML 1.0
title: sys-api-lead

  
/lead:
  get:
    queryParameters:
      Id:
        type: string
    responses:
      200:
        body:
          application/json:
            examples: 
              values:             
                [
                  {
                      "LastModifiedDate": "2024-09-07T04:03:24.000Z",
                      "Company": "20th century Movies",
                      "IsDeleted": "false",
                      "Email": "jenniferlawrence@jennifer.com",
                      "Address": null,
                      "IsConverted": "false",
                      "Title": "Director",
                      "type": "Lead",
                      "Name": "Jennifer Lawrence",
                      "Phone": "234567890",
                      "CreatedDate": "2024-09-06T17:52:49.000Z",
                      "Country": null,
                      "Id": "00QQH000007YBBW2A4"
                  }
                ]
      400:
        body:
          application/json:
            examples:
              values:
                message : "Bad request"
      401:
        body:
          application/json:
            examples:
              values:
                message : "Unauthorized" 
      404:
        body:
          application/json:
            examples:
              values:
                message : "Not Found"     
      500:
        body:
          application/json:
            examples:
              values:
                message : "Internal Sevor Error"  
  post:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    body:
      application/json:
        type: array
        items:
          type: object
          properties:
            Id:
              type: string
              required: false
            First Name:
              type: string
              required: false
            Last Name:
              type: string
              required: true
            Title:
              type: string
              required: false
            Company:
              type: string
              required: true
            Lead Status:
              type: string
              required: true
            Lead Source:
              type: string
              required: false
        examples: 
          values:               
            [
              {
                "First Name": "Amy",
                "Last Name" : "Jordan",
                "Title": "VP Purchasing",
                "Company":  "Lee Enterprise, Inc",
                "Lead Status" : "New",
                "Lead Source" : "Web",
                "Phone"  : "012345678",
                "Email" : "amyjordan1234@amy.com"
              }
            ]
    responses:
      201:
        body:
          application/json:
            examples:
              values:
                message : "Lead created successfully"
      400:
        body:
          application/json:
            examples:
              values:
                message : "Bad request"
      401:
        body:
          application/json:
            examples:
              values:
                message : "Unauthorized" 
      404:
        body:
          application/json:
            examples:
              values:
                message : "Not Found"     
      500:
        body:
          application/json:
            examples:
              values:
                message : "Internal Sevor Error"            
